modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LXGaming/Doot/issues"

[[mods]]
modId="doot"
version="${version}"
displayName="Doot"
displayURL="https://lxgaming.github.io/"
logoFile="lxgaming.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="Doot\nSource - https://github.com/LXGaming/Doot"